### Create user
POST http://localhost:3000/users
Content-Type: application/json


{
  "name": "email",
  "email": "email@email.com",
  "password": "password123",
  "role": "ADMIN"
}

###

### Get all users
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZW1haWwiLCJlbWFpbCI6ImVtYWlsQGVtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsInN1YiI6ImNtbDV4ZTA1ZjAwMDAwMW1uZ2txNjNrOGIiLCJpYXQiOjE3NzAwODI0ODgsImV4cCI6MTc3MDE2ODg4OH0.75bgCxfgIZp9GFeNnMQqH_KiBv0ifaYHvlQpAqc84YU

###

### Get user by id
GET http://localhost:3000/users/cml1kj89k0000w4iofzzjxjre

###

### Update user
PATCH http://localhost:3000/users/cml07v19r00021gio1dprax3v
Content-Type: application/json

{
 "password": "novaSenha123"
}

###

### Delete user
DELETE http://localhost:3000/users/cml07v19r00021gio1dprax3v  
