@baseUrl = http://localhost:3001
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtbWxkc3ZsYzAwMDBla2lvZmVranYybDgiLCJyb2xlIjoiQURNSU4iLCJjb2RlIjoiQURNSU4xMjMiLCJpYXQiOjE3NzM3MDgzODUsImV4cCI6MTc3Mzc5NDc4NX0.vTFZ2wcnvt4TjiGID7fyhxCAa0CHxCYLcO3fAp8ppzM


### Criar empresa
POST  {{baseUrl}}/users
Content-Type: application/json
Cookie: token={{token}}

{
  "code": "ADMIN123",
  "name": "Arthur Roberto",
  "role": "ADMIN"
}

### Listar empresas
GET {{baseUrl}}/company
Content-Type: application/json
Cookie: token={{token}}


### Buscar empresa por id
GET {{baseUrl}}/companies/COMPANY_ID
Cookie: token={{token}}


### Atualizar empresa
PATCH {{baseUrl}}/companies/COMPANY_ID
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Nubank Atualizado",
  "sector": "TECHNOLOGY"
}


### Deletar empresa
DELETE {{baseUrl}}/companies/COMPANY_ID
Authorization: Bearer {{token}}