@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXNlciIsImVtYWlsIjoidXNlckBlbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJzdWIiOiJjbWw4c3E4a2wwMDAwdm9pb2c5bWJ1eGlkIiwiaWF0IjoxNzcwMjU2MDUzLCJleHAiOjE3NzAzNDI0NTN9.JyaYsIGh9xphr57KyDcMiF2h5lBj1_W8yTymJgwszJw

POST http://localhost:3000/recipes
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "title":"Chocolate Cake",
  "description": "Simple chocolate cake",
  "ingredients": "Flour, sugar, cocoa, eggs",
  "instructions": "Mix everything and bake"
}

###

### Get all recipes
GET localhost:3000/recipes

###

### Get recipe by id
GET localhost:3000/recipes/id_da_receita

###

### Update recipe
PUT localhost:3000/recipes/id_da_receita
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "title": "Updated Chocolate Cake",
  "description": "Better chocolate cake"
}

###

### Delete recipe
DELETE localhost:3000/recipes/id_da_receita
Authorization: Bearer {{authToken}}